[mq_targets]
mqnode1 ansible_host=192.168.40.200 ansible_user=gannex ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/id_rsa ansible_become=true

[mq_nonprod]
mqnode1

[mq_prod]
; mqnode2
; mqnode3

[mq_future]
; mqnode2 ansible_host=192.168.40.201 ansible_user=gannex ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/id_rsa ansible_become=true
; mqnode3 ansible_host=192.168.40.202 ansible_user=gannex ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/id_rsa ansible_become=true
